/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogoVelha;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class TelaDoJogo extends javax.swing.JFrame {
    public int x[][] = new int[3][3];
    public int res[][] = new int[2][5];
    public int i, j;
    public int num;
    public boolean jogador = true;
    public boolean ganhador = false;
    public int pont1;
    public int pont2;
    public int jogo = 0;
    public int velha = 0;
    public int rodadas = 0;
    public String deuvelha = "deu velha";
    

    /**
     * Creates new form TelaDoJogo
     */
    public TelaDoJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton01 = new javax.swing.JButton();
        jButton02 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton00 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton01MouseClicked(evt);
            }
        });

        jButton02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton02MouseClicked(evt);
            }
        });

        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });

        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });

        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });

        jButton00.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton00MouseClicked(evt);
            }
        });

        jButton1.setText("jogar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jButton01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton02, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton00MouseClicked
        if(x[0][0] != 0 && x[0][0] != 1 && !ganhador){
            if(jogador){
            x[0][0] = 0;
            jButton00.setText("O");
        }else{
            x[0][0] = 1;
            jButton00.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton00MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int num = 2;
        for(i = 0; i < 3; i++){
            for(j = 0; j < 3; j++){
                x[i][j] = num;
                num++;
            }
        }
        jogador = true;
        ganhador = false;
        jButton1.setText("Jogar novamente "+(rodadas+1)+"/5");
        jButton00.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton01MouseClicked
        if(x[0][1] != 0 && x[0][1] != 1 && !ganhador){
            if(jogador){
            x[0][1] = 0;
            jButton01.setText("O");
        }else{
            x[0][1] = 1;
            jButton01.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton01MouseClicked

    private void jButton02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton02MouseClicked
        if(x[0][2] != 0 && x[0][2] != 1 && !ganhador){
            if(jogador){
            x[0][2] = 0;
            jButton02.setText("O");
        }else{
            x[0][2] = 1;
            jButton02.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton02MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if(x[1][0] != 0 && x[1][0] != 1 && !ganhador){
            if(jogador){
            x[1][0] = 0;
            jButton10.setText("O");
        }else{
            x[1][0] = 1;
            jButton10.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        if(x[1][1] != 0 && x[1][1] != 1 && !ganhador){
            if(jogador){
            x[1][1] = 0;
            jButton11.setText("O");
        }else{
            x[1][1] = 1;
            jButton11.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        if(x[1][2] != 0 && x[1][2] != 1 && !ganhador){
            if(jogador){
            x[1][2] = 0;
            jButton12.setText("O");
        }else{
            x[1][2] = 1;
            jButton12.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        if(x[2][0] != 0 && x[2][0] != 1 && !ganhador){
            if(jogador){
            x[2][0] = 0;
            jButton20.setText("O");
        }else{
            x[2][0] = 1;
            jButton20.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        if(x[2][1] != 0 && x[2][1] != 1 && !ganhador){
            if(jogador){
            x[2][1] = 0;
            jButton21.setText("O");
        }else{
            x[2][1] = 1;
            jButton21.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        if(x[2][2] != 0 && x[2][2] != 1 && !ganhador){
            if(jogador){
            x[2][2] = 0;
            jButton22.setText("O");
        }else{
            x[2][2] = 1;
            jButton22.setText("X");
        }
        sansung();
        }
    }//GEN-LAST:event_jButton22MouseClicked

    public void sansung(){
        for(i = 0; i < 3; i++){
            if(x[i][0] == x[i][1] && x[i][0] == x[i][2]) ganhador = true; //checando ganhador linha
            if(x[0][i] == x[1][i] && x[0][i] == x[2][i]) ganhador = true; // checando ganhador coluna
        }
        if(x[0][0] == x[1][1] && x[0][0] == x[2][2]) ganhador = true; //checando diagonal principal
        if(x[2][0] == x[1][1] && x[1][1] == x[0][2]) ganhador = true; // checando diagonal secundaria
        
        velha ++;
        if(ganhador){
            int num = 2;
            for(i = 0; i < 3; i++){
                for(j = 0; j < 3; j++){
                x[i][j] = num;
                num++;
                }
            }
            if(jogador){
                res[0][rodadas] = res[0][rodadas] + 5;
                JOptionPane.showInternalMessageDialog(null,"Jogador O ganhou");
            }else{
                res[1][rodadas] = res[0][rodadas] + 5;
                JOptionPane.showInternalMessageDialog(null,"Jogador X ganhou");
            }
            rodadas++;
            velha = 0;
        }else{
            if(velha == 9){
                res[0][rodadas] = res[0][rodadas] + 2;
                res[1][rodadas] = res[0][rodadas] + 2;
                JOptionPane.showInternalMessageDialog(null,"Velha");
                rodadas++;
                velha = 0;
            }
        jogador = !jogador;
    }
    }
    public void limpeza(){
        jButton00.setText("");
        jButton01.setText("");
        jButton02.setText("");
        jButton10.setText("");
        jButton11.setText("");
        jButton12.setText("");
        jButton20.setText("");
        jButton21.setText("");
        jButton22.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton00;
    private javax.swing.JButton jButton01;
    private javax.swing.JButton jButton02;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    // End of variables declaration//GEN-END:variables
}
